### ISSUE TITLE
GlideApp

### ISSUE THREAD

**Issue by kumarkumar217** [nuhkoca/GlideAppModuleSample#1]
I have download this code. And it is working fine. I want to save images on custom folder. Do you have any solution for it?

**Comment by nuhkoca** [comment]
Hi @kumarkumar217 ,

Thanks for creating the issue. I have implemented a sample image saving on the branch [feature/image_save ](https://github.com/nuhkoca/GlideAppModuleSample/tree/feature/image_save)

You are welcome to have a look at it and give feedback :)
